// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: speechly/slu/v1/wlu.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_speechly_2fslu_2fv1_2fwlu_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_speechly_2fslu_2fv1_2fwlu_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3017000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3017003 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_speechly_2fslu_2fv1_2fwlu_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_speechly_2fslu_2fv1_2fwlu_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[6]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_speechly_2fslu_2fv1_2fwlu_2eproto;
namespace speechly {
namespace slu {
namespace v1 {
class WLUEntity;
struct WLUEntityDefaultTypeInternal;
extern WLUEntityDefaultTypeInternal _WLUEntity_default_instance_;
class WLUIntent;
struct WLUIntentDefaultTypeInternal;
extern WLUIntentDefaultTypeInternal _WLUIntent_default_instance_;
class WLURequest;
struct WLURequestDefaultTypeInternal;
extern WLURequestDefaultTypeInternal _WLURequest_default_instance_;
class WLUResponse;
struct WLUResponseDefaultTypeInternal;
extern WLUResponseDefaultTypeInternal _WLUResponse_default_instance_;
class WLUSegment;
struct WLUSegmentDefaultTypeInternal;
extern WLUSegmentDefaultTypeInternal _WLUSegment_default_instance_;
class WLUToken;
struct WLUTokenDefaultTypeInternal;
extern WLUTokenDefaultTypeInternal _WLUToken_default_instance_;
}  // namespace v1
}  // namespace slu
}  // namespace speechly
PROTOBUF_NAMESPACE_OPEN
template<> ::speechly::slu::v1::WLUEntity* Arena::CreateMaybeMessage<::speechly::slu::v1::WLUEntity>(Arena*);
template<> ::speechly::slu::v1::WLUIntent* Arena::CreateMaybeMessage<::speechly::slu::v1::WLUIntent>(Arena*);
template<> ::speechly::slu::v1::WLURequest* Arena::CreateMaybeMessage<::speechly::slu::v1::WLURequest>(Arena*);
template<> ::speechly::slu::v1::WLUResponse* Arena::CreateMaybeMessage<::speechly::slu::v1::WLUResponse>(Arena*);
template<> ::speechly::slu::v1::WLUSegment* Arena::CreateMaybeMessage<::speechly::slu::v1::WLUSegment>(Arena*);
template<> ::speechly::slu::v1::WLUToken* Arena::CreateMaybeMessage<::speechly::slu::v1::WLUToken>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace speechly {
namespace slu {
namespace v1 {

// ===================================================================

class WLURequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:speechly.slu.v1.WLURequest) */ {
 public:
  inline WLURequest() : WLURequest(nullptr) {}
  ~WLURequest() override;
  explicit constexpr WLURequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  WLURequest(const WLURequest& from);
  WLURequest(WLURequest&& from) noexcept
    : WLURequest() {
    *this = ::std::move(from);
  }

  inline WLURequest& operator=(const WLURequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline WLURequest& operator=(WLURequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const WLURequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const WLURequest* internal_default_instance() {
    return reinterpret_cast<const WLURequest*>(
               &_WLURequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(WLURequest& a, WLURequest& b) {
    a.Swap(&b);
  }
  inline void Swap(WLURequest* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(WLURequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline WLURequest* New() const final {
    return new WLURequest();
  }

  WLURequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<WLURequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const WLURequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const WLURequest& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message*to, const ::PROTOBUF_NAMESPACE_ID::Message&from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(WLURequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "speechly.slu.v1.WLURequest";
  }
  protected:
  explicit WLURequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLanguageCodeFieldNumber = 1,
    kTextFieldNumber = 2,
  };
  // string language_code = 1;
  void clear_language_code();
  const std::string& language_code() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_language_code(ArgT0&& arg0, ArgT... args);
  std::string* mutable_language_code();
  PROTOBUF_MUST_USE_RESULT std::string* release_language_code();
  void set_allocated_language_code(std::string* language_code);
  private:
  const std::string& _internal_language_code() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_language_code(const std::string& value);
  std::string* _internal_mutable_language_code();
  public:

  // string text = 2;
  void clear_text();
  const std::string& text() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_text(ArgT0&& arg0, ArgT... args);
  std::string* mutable_text();
  PROTOBUF_MUST_USE_RESULT std::string* release_text();
  void set_allocated_text(std::string* text);
  private:
  const std::string& _internal_text() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_text(const std::string& value);
  std::string* _internal_mutable_text();
  public:

  // @@protoc_insertion_point(class_scope:speechly.slu.v1.WLURequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr language_code_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr text_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_speechly_2fslu_2fv1_2fwlu_2eproto;
};
// -------------------------------------------------------------------

class WLUResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:speechly.slu.v1.WLUResponse) */ {
 public:
  inline WLUResponse() : WLUResponse(nullptr) {}
  ~WLUResponse() override;
  explicit constexpr WLUResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  WLUResponse(const WLUResponse& from);
  WLUResponse(WLUResponse&& from) noexcept
    : WLUResponse() {
    *this = ::std::move(from);
  }

  inline WLUResponse& operator=(const WLUResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline WLUResponse& operator=(WLUResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const WLUResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const WLUResponse* internal_default_instance() {
    return reinterpret_cast<const WLUResponse*>(
               &_WLUResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(WLUResponse& a, WLUResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(WLUResponse* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(WLUResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline WLUResponse* New() const final {
    return new WLUResponse();
  }

  WLUResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<WLUResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const WLUResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const WLUResponse& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message*to, const ::PROTOBUF_NAMESPACE_ID::Message&from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(WLUResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "speechly.slu.v1.WLUResponse";
  }
  protected:
  explicit WLUResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSegmentsFieldNumber = 1,
  };
  // repeated .speechly.slu.v1.WLUSegment segments = 1;
  int segments_size() const;
  private:
  int _internal_segments_size() const;
  public:
  void clear_segments();
  ::speechly::slu::v1::WLUSegment* mutable_segments(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::speechly::slu::v1::WLUSegment >*
      mutable_segments();
  private:
  const ::speechly::slu::v1::WLUSegment& _internal_segments(int index) const;
  ::speechly::slu::v1::WLUSegment* _internal_add_segments();
  public:
  const ::speechly::slu::v1::WLUSegment& segments(int index) const;
  ::speechly::slu::v1::WLUSegment* add_segments();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::speechly::slu::v1::WLUSegment >&
      segments() const;

  // @@protoc_insertion_point(class_scope:speechly.slu.v1.WLUResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::speechly::slu::v1::WLUSegment > segments_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_speechly_2fslu_2fv1_2fwlu_2eproto;
};
// -------------------------------------------------------------------

class WLUSegment final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:speechly.slu.v1.WLUSegment) */ {
 public:
  inline WLUSegment() : WLUSegment(nullptr) {}
  ~WLUSegment() override;
  explicit constexpr WLUSegment(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  WLUSegment(const WLUSegment& from);
  WLUSegment(WLUSegment&& from) noexcept
    : WLUSegment() {
    *this = ::std::move(from);
  }

  inline WLUSegment& operator=(const WLUSegment& from) {
    CopyFrom(from);
    return *this;
  }
  inline WLUSegment& operator=(WLUSegment&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const WLUSegment& default_instance() {
    return *internal_default_instance();
  }
  static inline const WLUSegment* internal_default_instance() {
    return reinterpret_cast<const WLUSegment*>(
               &_WLUSegment_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(WLUSegment& a, WLUSegment& b) {
    a.Swap(&b);
  }
  inline void Swap(WLUSegment* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(WLUSegment* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline WLUSegment* New() const final {
    return new WLUSegment();
  }

  WLUSegment* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<WLUSegment>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const WLUSegment& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const WLUSegment& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message*to, const ::PROTOBUF_NAMESPACE_ID::Message&from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(WLUSegment* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "speechly.slu.v1.WLUSegment";
  }
  protected:
  explicit WLUSegment(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTokensFieldNumber = 2,
    kEntitiesFieldNumber = 3,
    kTextFieldNumber = 1,
    kIntentFieldNumber = 4,
  };
  // repeated .speechly.slu.v1.WLUToken tokens = 2;
  int tokens_size() const;
  private:
  int _internal_tokens_size() const;
  public:
  void clear_tokens();
  ::speechly::slu::v1::WLUToken* mutable_tokens(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::speechly::slu::v1::WLUToken >*
      mutable_tokens();
  private:
  const ::speechly::slu::v1::WLUToken& _internal_tokens(int index) const;
  ::speechly::slu::v1::WLUToken* _internal_add_tokens();
  public:
  const ::speechly::slu::v1::WLUToken& tokens(int index) const;
  ::speechly::slu::v1::WLUToken* add_tokens();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::speechly::slu::v1::WLUToken >&
      tokens() const;

  // repeated .speechly.slu.v1.WLUEntity entities = 3;
  int entities_size() const;
  private:
  int _internal_entities_size() const;
  public:
  void clear_entities();
  ::speechly::slu::v1::WLUEntity* mutable_entities(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::speechly::slu::v1::WLUEntity >*
      mutable_entities();
  private:
  const ::speechly::slu::v1::WLUEntity& _internal_entities(int index) const;
  ::speechly::slu::v1::WLUEntity* _internal_add_entities();
  public:
  const ::speechly::slu::v1::WLUEntity& entities(int index) const;
  ::speechly::slu::v1::WLUEntity* add_entities();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::speechly::slu::v1::WLUEntity >&
      entities() const;

  // string text = 1;
  void clear_text();
  const std::string& text() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_text(ArgT0&& arg0, ArgT... args);
  std::string* mutable_text();
  PROTOBUF_MUST_USE_RESULT std::string* release_text();
  void set_allocated_text(std::string* text);
  private:
  const std::string& _internal_text() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_text(const std::string& value);
  std::string* _internal_mutable_text();
  public:

  // .speechly.slu.v1.WLUIntent intent = 4;
  bool has_intent() const;
  private:
  bool _internal_has_intent() const;
  public:
  void clear_intent();
  const ::speechly::slu::v1::WLUIntent& intent() const;
  PROTOBUF_MUST_USE_RESULT ::speechly::slu::v1::WLUIntent* release_intent();
  ::speechly::slu::v1::WLUIntent* mutable_intent();
  void set_allocated_intent(::speechly::slu::v1::WLUIntent* intent);
  private:
  const ::speechly::slu::v1::WLUIntent& _internal_intent() const;
  ::speechly::slu::v1::WLUIntent* _internal_mutable_intent();
  public:
  void unsafe_arena_set_allocated_intent(
      ::speechly::slu::v1::WLUIntent* intent);
  ::speechly::slu::v1::WLUIntent* unsafe_arena_release_intent();

  // @@protoc_insertion_point(class_scope:speechly.slu.v1.WLUSegment)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::speechly::slu::v1::WLUToken > tokens_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::speechly::slu::v1::WLUEntity > entities_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr text_;
  ::speechly::slu::v1::WLUIntent* intent_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_speechly_2fslu_2fv1_2fwlu_2eproto;
};
// -------------------------------------------------------------------

class WLUToken final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:speechly.slu.v1.WLUToken) */ {
 public:
  inline WLUToken() : WLUToken(nullptr) {}
  ~WLUToken() override;
  explicit constexpr WLUToken(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  WLUToken(const WLUToken& from);
  WLUToken(WLUToken&& from) noexcept
    : WLUToken() {
    *this = ::std::move(from);
  }

  inline WLUToken& operator=(const WLUToken& from) {
    CopyFrom(from);
    return *this;
  }
  inline WLUToken& operator=(WLUToken&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const WLUToken& default_instance() {
    return *internal_default_instance();
  }
  static inline const WLUToken* internal_default_instance() {
    return reinterpret_cast<const WLUToken*>(
               &_WLUToken_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(WLUToken& a, WLUToken& b) {
    a.Swap(&b);
  }
  inline void Swap(WLUToken* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(WLUToken* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline WLUToken* New() const final {
    return new WLUToken();
  }

  WLUToken* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<WLUToken>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const WLUToken& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const WLUToken& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message*to, const ::PROTOBUF_NAMESPACE_ID::Message&from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(WLUToken* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "speechly.slu.v1.WLUToken";
  }
  protected:
  explicit WLUToken(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kWordFieldNumber = 1,
    kIndexFieldNumber = 2,
  };
  // string word = 1;
  void clear_word();
  const std::string& word() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_word(ArgT0&& arg0, ArgT... args);
  std::string* mutable_word();
  PROTOBUF_MUST_USE_RESULT std::string* release_word();
  void set_allocated_word(std::string* word);
  private:
  const std::string& _internal_word() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_word(const std::string& value);
  std::string* _internal_mutable_word();
  public:

  // int32 index = 2;
  void clear_index();
  ::PROTOBUF_NAMESPACE_ID::int32 index() const;
  void set_index(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_index() const;
  void _internal_set_index(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:speechly.slu.v1.WLUToken)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr word_;
  ::PROTOBUF_NAMESPACE_ID::int32 index_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_speechly_2fslu_2fv1_2fwlu_2eproto;
};
// -------------------------------------------------------------------

class WLUEntity final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:speechly.slu.v1.WLUEntity) */ {
 public:
  inline WLUEntity() : WLUEntity(nullptr) {}
  ~WLUEntity() override;
  explicit constexpr WLUEntity(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  WLUEntity(const WLUEntity& from);
  WLUEntity(WLUEntity&& from) noexcept
    : WLUEntity() {
    *this = ::std::move(from);
  }

  inline WLUEntity& operator=(const WLUEntity& from) {
    CopyFrom(from);
    return *this;
  }
  inline WLUEntity& operator=(WLUEntity&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const WLUEntity& default_instance() {
    return *internal_default_instance();
  }
  static inline const WLUEntity* internal_default_instance() {
    return reinterpret_cast<const WLUEntity*>(
               &_WLUEntity_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(WLUEntity& a, WLUEntity& b) {
    a.Swap(&b);
  }
  inline void Swap(WLUEntity* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(WLUEntity* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline WLUEntity* New() const final {
    return new WLUEntity();
  }

  WLUEntity* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<WLUEntity>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const WLUEntity& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const WLUEntity& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message*to, const ::PROTOBUF_NAMESPACE_ID::Message&from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(WLUEntity* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "speechly.slu.v1.WLUEntity";
  }
  protected:
  explicit WLUEntity(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kEntityFieldNumber = 1,
    kValueFieldNumber = 2,
    kStartPositionFieldNumber = 3,
    kEndPositionFieldNumber = 4,
  };
  // string entity = 1;
  void clear_entity();
  const std::string& entity() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_entity(ArgT0&& arg0, ArgT... args);
  std::string* mutable_entity();
  PROTOBUF_MUST_USE_RESULT std::string* release_entity();
  void set_allocated_entity(std::string* entity);
  private:
  const std::string& _internal_entity() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_entity(const std::string& value);
  std::string* _internal_mutable_entity();
  public:

  // string value = 2;
  void clear_value();
  const std::string& value() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_value(ArgT0&& arg0, ArgT... args);
  std::string* mutable_value();
  PROTOBUF_MUST_USE_RESULT std::string* release_value();
  void set_allocated_value(std::string* value);
  private:
  const std::string& _internal_value() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_value(const std::string& value);
  std::string* _internal_mutable_value();
  public:

  // int32 start_position = 3;
  void clear_start_position();
  ::PROTOBUF_NAMESPACE_ID::int32 start_position() const;
  void set_start_position(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_start_position() const;
  void _internal_set_start_position(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 end_position = 4;
  void clear_end_position();
  ::PROTOBUF_NAMESPACE_ID::int32 end_position() const;
  void set_end_position(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_end_position() const;
  void _internal_set_end_position(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:speechly.slu.v1.WLUEntity)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr entity_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr value_;
  ::PROTOBUF_NAMESPACE_ID::int32 start_position_;
  ::PROTOBUF_NAMESPACE_ID::int32 end_position_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_speechly_2fslu_2fv1_2fwlu_2eproto;
};
// -------------------------------------------------------------------

class WLUIntent final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:speechly.slu.v1.WLUIntent) */ {
 public:
  inline WLUIntent() : WLUIntent(nullptr) {}
  ~WLUIntent() override;
  explicit constexpr WLUIntent(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  WLUIntent(const WLUIntent& from);
  WLUIntent(WLUIntent&& from) noexcept
    : WLUIntent() {
    *this = ::std::move(from);
  }

  inline WLUIntent& operator=(const WLUIntent& from) {
    CopyFrom(from);
    return *this;
  }
  inline WLUIntent& operator=(WLUIntent&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const WLUIntent& default_instance() {
    return *internal_default_instance();
  }
  static inline const WLUIntent* internal_default_instance() {
    return reinterpret_cast<const WLUIntent*>(
               &_WLUIntent_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(WLUIntent& a, WLUIntent& b) {
    a.Swap(&b);
  }
  inline void Swap(WLUIntent* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(WLUIntent* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline WLUIntent* New() const final {
    return new WLUIntent();
  }

  WLUIntent* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<WLUIntent>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const WLUIntent& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const WLUIntent& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message*to, const ::PROTOBUF_NAMESPACE_ID::Message&from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(WLUIntent* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "speechly.slu.v1.WLUIntent";
  }
  protected:
  explicit WLUIntent(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIntentFieldNumber = 1,
  };
  // string intent = 1;
  void clear_intent();
  const std::string& intent() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_intent(ArgT0&& arg0, ArgT... args);
  std::string* mutable_intent();
  PROTOBUF_MUST_USE_RESULT std::string* release_intent();
  void set_allocated_intent(std::string* intent);
  private:
  const std::string& _internal_intent() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_intent(const std::string& value);
  std::string* _internal_mutable_intent();
  public:

  // @@protoc_insertion_point(class_scope:speechly.slu.v1.WLUIntent)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr intent_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_speechly_2fslu_2fv1_2fwlu_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// WLURequest

// string language_code = 1;
inline void WLURequest::clear_language_code() {
  language_code_.ClearToEmpty();
}
inline const std::string& WLURequest::language_code() const {
  // @@protoc_insertion_point(field_get:speechly.slu.v1.WLURequest.language_code)
  return _internal_language_code();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void WLURequest::set_language_code(ArgT0&& arg0, ArgT... args) {
 
 language_code_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:speechly.slu.v1.WLURequest.language_code)
}
inline std::string* WLURequest::mutable_language_code() {
  std::string* _s = _internal_mutable_language_code();
  // @@protoc_insertion_point(field_mutable:speechly.slu.v1.WLURequest.language_code)
  return _s;
}
inline const std::string& WLURequest::_internal_language_code() const {
  return language_code_.Get();
}
inline void WLURequest::_internal_set_language_code(const std::string& value) {
  
  language_code_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* WLURequest::_internal_mutable_language_code() {
  
  return language_code_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* WLURequest::release_language_code() {
  // @@protoc_insertion_point(field_release:speechly.slu.v1.WLURequest.language_code)
  return language_code_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void WLURequest::set_allocated_language_code(std::string* language_code) {
  if (language_code != nullptr) {
    
  } else {
    
  }
  language_code_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), language_code,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:speechly.slu.v1.WLURequest.language_code)
}

// string text = 2;
inline void WLURequest::clear_text() {
  text_.ClearToEmpty();
}
inline const std::string& WLURequest::text() const {
  // @@protoc_insertion_point(field_get:speechly.slu.v1.WLURequest.text)
  return _internal_text();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void WLURequest::set_text(ArgT0&& arg0, ArgT... args) {
 
 text_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:speechly.slu.v1.WLURequest.text)
}
inline std::string* WLURequest::mutable_text() {
  std::string* _s = _internal_mutable_text();
  // @@protoc_insertion_point(field_mutable:speechly.slu.v1.WLURequest.text)
  return _s;
}
inline const std::string& WLURequest::_internal_text() const {
  return text_.Get();
}
inline void WLURequest::_internal_set_text(const std::string& value) {
  
  text_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* WLURequest::_internal_mutable_text() {
  
  return text_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* WLURequest::release_text() {
  // @@protoc_insertion_point(field_release:speechly.slu.v1.WLURequest.text)
  return text_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void WLURequest::set_allocated_text(std::string* text) {
  if (text != nullptr) {
    
  } else {
    
  }
  text_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), text,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:speechly.slu.v1.WLURequest.text)
}

// -------------------------------------------------------------------

// WLUResponse

// repeated .speechly.slu.v1.WLUSegment segments = 1;
inline int WLUResponse::_internal_segments_size() const {
  return segments_.size();
}
inline int WLUResponse::segments_size() const {
  return _internal_segments_size();
}
inline void WLUResponse::clear_segments() {
  segments_.Clear();
}
inline ::speechly::slu::v1::WLUSegment* WLUResponse::mutable_segments(int index) {
  // @@protoc_insertion_point(field_mutable:speechly.slu.v1.WLUResponse.segments)
  return segments_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::speechly::slu::v1::WLUSegment >*
WLUResponse::mutable_segments() {
  // @@protoc_insertion_point(field_mutable_list:speechly.slu.v1.WLUResponse.segments)
  return &segments_;
}
inline const ::speechly::slu::v1::WLUSegment& WLUResponse::_internal_segments(int index) const {
  return segments_.Get(index);
}
inline const ::speechly::slu::v1::WLUSegment& WLUResponse::segments(int index) const {
  // @@protoc_insertion_point(field_get:speechly.slu.v1.WLUResponse.segments)
  return _internal_segments(index);
}
inline ::speechly::slu::v1::WLUSegment* WLUResponse::_internal_add_segments() {
  return segments_.Add();
}
inline ::speechly::slu::v1::WLUSegment* WLUResponse::add_segments() {
  ::speechly::slu::v1::WLUSegment* _add = _internal_add_segments();
  // @@protoc_insertion_point(field_add:speechly.slu.v1.WLUResponse.segments)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::speechly::slu::v1::WLUSegment >&
WLUResponse::segments() const {
  // @@protoc_insertion_point(field_list:speechly.slu.v1.WLUResponse.segments)
  return segments_;
}

// -------------------------------------------------------------------

// WLUSegment

// string text = 1;
inline void WLUSegment::clear_text() {
  text_.ClearToEmpty();
}
inline const std::string& WLUSegment::text() const {
  // @@protoc_insertion_point(field_get:speechly.slu.v1.WLUSegment.text)
  return _internal_text();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void WLUSegment::set_text(ArgT0&& arg0, ArgT... args) {
 
 text_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:speechly.slu.v1.WLUSegment.text)
}
inline std::string* WLUSegment::mutable_text() {
  std::string* _s = _internal_mutable_text();
  // @@protoc_insertion_point(field_mutable:speechly.slu.v1.WLUSegment.text)
  return _s;
}
inline const std::string& WLUSegment::_internal_text() const {
  return text_.Get();
}
inline void WLUSegment::_internal_set_text(const std::string& value) {
  
  text_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* WLUSegment::_internal_mutable_text() {
  
  return text_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* WLUSegment::release_text() {
  // @@protoc_insertion_point(field_release:speechly.slu.v1.WLUSegment.text)
  return text_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void WLUSegment::set_allocated_text(std::string* text) {
  if (text != nullptr) {
    
  } else {
    
  }
  text_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), text,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:speechly.slu.v1.WLUSegment.text)
}

// repeated .speechly.slu.v1.WLUToken tokens = 2;
inline int WLUSegment::_internal_tokens_size() const {
  return tokens_.size();
}
inline int WLUSegment::tokens_size() const {
  return _internal_tokens_size();
}
inline void WLUSegment::clear_tokens() {
  tokens_.Clear();
}
inline ::speechly::slu::v1::WLUToken* WLUSegment::mutable_tokens(int index) {
  // @@protoc_insertion_point(field_mutable:speechly.slu.v1.WLUSegment.tokens)
  return tokens_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::speechly::slu::v1::WLUToken >*
WLUSegment::mutable_tokens() {
  // @@protoc_insertion_point(field_mutable_list:speechly.slu.v1.WLUSegment.tokens)
  return &tokens_;
}
inline const ::speechly::slu::v1::WLUToken& WLUSegment::_internal_tokens(int index) const {
  return tokens_.Get(index);
}
inline const ::speechly::slu::v1::WLUToken& WLUSegment::tokens(int index) const {
  // @@protoc_insertion_point(field_get:speechly.slu.v1.WLUSegment.tokens)
  return _internal_tokens(index);
}
inline ::speechly::slu::v1::WLUToken* WLUSegment::_internal_add_tokens() {
  return tokens_.Add();
}
inline ::speechly::slu::v1::WLUToken* WLUSegment::add_tokens() {
  ::speechly::slu::v1::WLUToken* _add = _internal_add_tokens();
  // @@protoc_insertion_point(field_add:speechly.slu.v1.WLUSegment.tokens)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::speechly::slu::v1::WLUToken >&
WLUSegment::tokens() const {
  // @@protoc_insertion_point(field_list:speechly.slu.v1.WLUSegment.tokens)
  return tokens_;
}

// repeated .speechly.slu.v1.WLUEntity entities = 3;
inline int WLUSegment::_internal_entities_size() const {
  return entities_.size();
}
inline int WLUSegment::entities_size() const {
  return _internal_entities_size();
}
inline void WLUSegment::clear_entities() {
  entities_.Clear();
}
inline ::speechly::slu::v1::WLUEntity* WLUSegment::mutable_entities(int index) {
  // @@protoc_insertion_point(field_mutable:speechly.slu.v1.WLUSegment.entities)
  return entities_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::speechly::slu::v1::WLUEntity >*
WLUSegment::mutable_entities() {
  // @@protoc_insertion_point(field_mutable_list:speechly.slu.v1.WLUSegment.entities)
  return &entities_;
}
inline const ::speechly::slu::v1::WLUEntity& WLUSegment::_internal_entities(int index) const {
  return entities_.Get(index);
}
inline const ::speechly::slu::v1::WLUEntity& WLUSegment::entities(int index) const {
  // @@protoc_insertion_point(field_get:speechly.slu.v1.WLUSegment.entities)
  return _internal_entities(index);
}
inline ::speechly::slu::v1::WLUEntity* WLUSegment::_internal_add_entities() {
  return entities_.Add();
}
inline ::speechly::slu::v1::WLUEntity* WLUSegment::add_entities() {
  ::speechly::slu::v1::WLUEntity* _add = _internal_add_entities();
  // @@protoc_insertion_point(field_add:speechly.slu.v1.WLUSegment.entities)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::speechly::slu::v1::WLUEntity >&
WLUSegment::entities() const {
  // @@protoc_insertion_point(field_list:speechly.slu.v1.WLUSegment.entities)
  return entities_;
}

// .speechly.slu.v1.WLUIntent intent = 4;
inline bool WLUSegment::_internal_has_intent() const {
  return this != internal_default_instance() && intent_ != nullptr;
}
inline bool WLUSegment::has_intent() const {
  return _internal_has_intent();
}
inline void WLUSegment::clear_intent() {
  if (GetArenaForAllocation() == nullptr && intent_ != nullptr) {
    delete intent_;
  }
  intent_ = nullptr;
}
inline const ::speechly::slu::v1::WLUIntent& WLUSegment::_internal_intent() const {
  const ::speechly::slu::v1::WLUIntent* p = intent_;
  return p != nullptr ? *p : reinterpret_cast<const ::speechly::slu::v1::WLUIntent&>(
      ::speechly::slu::v1::_WLUIntent_default_instance_);
}
inline const ::speechly::slu::v1::WLUIntent& WLUSegment::intent() const {
  // @@protoc_insertion_point(field_get:speechly.slu.v1.WLUSegment.intent)
  return _internal_intent();
}
inline void WLUSegment::unsafe_arena_set_allocated_intent(
    ::speechly::slu::v1::WLUIntent* intent) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(intent_);
  }
  intent_ = intent;
  if (intent) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:speechly.slu.v1.WLUSegment.intent)
}
inline ::speechly::slu::v1::WLUIntent* WLUSegment::release_intent() {
  
  ::speechly::slu::v1::WLUIntent* temp = intent_;
  intent_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::speechly::slu::v1::WLUIntent* WLUSegment::unsafe_arena_release_intent() {
  // @@protoc_insertion_point(field_release:speechly.slu.v1.WLUSegment.intent)
  
  ::speechly::slu::v1::WLUIntent* temp = intent_;
  intent_ = nullptr;
  return temp;
}
inline ::speechly::slu::v1::WLUIntent* WLUSegment::_internal_mutable_intent() {
  
  if (intent_ == nullptr) {
    auto* p = CreateMaybeMessage<::speechly::slu::v1::WLUIntent>(GetArenaForAllocation());
    intent_ = p;
  }
  return intent_;
}
inline ::speechly::slu::v1::WLUIntent* WLUSegment::mutable_intent() {
  ::speechly::slu::v1::WLUIntent* _msg = _internal_mutable_intent();
  // @@protoc_insertion_point(field_mutable:speechly.slu.v1.WLUSegment.intent)
  return _msg;
}
inline void WLUSegment::set_allocated_intent(::speechly::slu::v1::WLUIntent* intent) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete intent_;
  }
  if (intent) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<::speechly::slu::v1::WLUIntent>::GetOwningArena(intent);
    if (message_arena != submessage_arena) {
      intent = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, intent, submessage_arena);
    }
    
  } else {
    
  }
  intent_ = intent;
  // @@protoc_insertion_point(field_set_allocated:speechly.slu.v1.WLUSegment.intent)
}

// -------------------------------------------------------------------

// WLUToken

// string word = 1;
inline void WLUToken::clear_word() {
  word_.ClearToEmpty();
}
inline const std::string& WLUToken::word() const {
  // @@protoc_insertion_point(field_get:speechly.slu.v1.WLUToken.word)
  return _internal_word();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void WLUToken::set_word(ArgT0&& arg0, ArgT... args) {
 
 word_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:speechly.slu.v1.WLUToken.word)
}
inline std::string* WLUToken::mutable_word() {
  std::string* _s = _internal_mutable_word();
  // @@protoc_insertion_point(field_mutable:speechly.slu.v1.WLUToken.word)
  return _s;
}
inline const std::string& WLUToken::_internal_word() const {
  return word_.Get();
}
inline void WLUToken::_internal_set_word(const std::string& value) {
  
  word_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* WLUToken::_internal_mutable_word() {
  
  return word_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* WLUToken::release_word() {
  // @@protoc_insertion_point(field_release:speechly.slu.v1.WLUToken.word)
  return word_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void WLUToken::set_allocated_word(std::string* word) {
  if (word != nullptr) {
    
  } else {
    
  }
  word_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), word,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:speechly.slu.v1.WLUToken.word)
}

// int32 index = 2;
inline void WLUToken::clear_index() {
  index_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 WLUToken::_internal_index() const {
  return index_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 WLUToken::index() const {
  // @@protoc_insertion_point(field_get:speechly.slu.v1.WLUToken.index)
  return _internal_index();
}
inline void WLUToken::_internal_set_index(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  index_ = value;
}
inline void WLUToken::set_index(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_index(value);
  // @@protoc_insertion_point(field_set:speechly.slu.v1.WLUToken.index)
}

// -------------------------------------------------------------------

// WLUEntity

// string entity = 1;
inline void WLUEntity::clear_entity() {
  entity_.ClearToEmpty();
}
inline const std::string& WLUEntity::entity() const {
  // @@protoc_insertion_point(field_get:speechly.slu.v1.WLUEntity.entity)
  return _internal_entity();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void WLUEntity::set_entity(ArgT0&& arg0, ArgT... args) {
 
 entity_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:speechly.slu.v1.WLUEntity.entity)
}
inline std::string* WLUEntity::mutable_entity() {
  std::string* _s = _internal_mutable_entity();
  // @@protoc_insertion_point(field_mutable:speechly.slu.v1.WLUEntity.entity)
  return _s;
}
inline const std::string& WLUEntity::_internal_entity() const {
  return entity_.Get();
}
inline void WLUEntity::_internal_set_entity(const std::string& value) {
  
  entity_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* WLUEntity::_internal_mutable_entity() {
  
  return entity_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* WLUEntity::release_entity() {
  // @@protoc_insertion_point(field_release:speechly.slu.v1.WLUEntity.entity)
  return entity_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void WLUEntity::set_allocated_entity(std::string* entity) {
  if (entity != nullptr) {
    
  } else {
    
  }
  entity_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), entity,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:speechly.slu.v1.WLUEntity.entity)
}

// string value = 2;
inline void WLUEntity::clear_value() {
  value_.ClearToEmpty();
}
inline const std::string& WLUEntity::value() const {
  // @@protoc_insertion_point(field_get:speechly.slu.v1.WLUEntity.value)
  return _internal_value();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void WLUEntity::set_value(ArgT0&& arg0, ArgT... args) {
 
 value_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:speechly.slu.v1.WLUEntity.value)
}
inline std::string* WLUEntity::mutable_value() {
  std::string* _s = _internal_mutable_value();
  // @@protoc_insertion_point(field_mutable:speechly.slu.v1.WLUEntity.value)
  return _s;
}
inline const std::string& WLUEntity::_internal_value() const {
  return value_.Get();
}
inline void WLUEntity::_internal_set_value(const std::string& value) {
  
  value_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* WLUEntity::_internal_mutable_value() {
  
  return value_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* WLUEntity::release_value() {
  // @@protoc_insertion_point(field_release:speechly.slu.v1.WLUEntity.value)
  return value_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void WLUEntity::set_allocated_value(std::string* value) {
  if (value != nullptr) {
    
  } else {
    
  }
  value_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:speechly.slu.v1.WLUEntity.value)
}

// int32 start_position = 3;
inline void WLUEntity::clear_start_position() {
  start_position_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 WLUEntity::_internal_start_position() const {
  return start_position_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 WLUEntity::start_position() const {
  // @@protoc_insertion_point(field_get:speechly.slu.v1.WLUEntity.start_position)
  return _internal_start_position();
}
inline void WLUEntity::_internal_set_start_position(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  start_position_ = value;
}
inline void WLUEntity::set_start_position(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_start_position(value);
  // @@protoc_insertion_point(field_set:speechly.slu.v1.WLUEntity.start_position)
}

// int32 end_position = 4;
inline void WLUEntity::clear_end_position() {
  end_position_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 WLUEntity::_internal_end_position() const {
  return end_position_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 WLUEntity::end_position() const {
  // @@protoc_insertion_point(field_get:speechly.slu.v1.WLUEntity.end_position)
  return _internal_end_position();
}
inline void WLUEntity::_internal_set_end_position(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  end_position_ = value;
}
inline void WLUEntity::set_end_position(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_end_position(value);
  // @@protoc_insertion_point(field_set:speechly.slu.v1.WLUEntity.end_position)
}

// -------------------------------------------------------------------

// WLUIntent

// string intent = 1;
inline void WLUIntent::clear_intent() {
  intent_.ClearToEmpty();
}
inline const std::string& WLUIntent::intent() const {
  // @@protoc_insertion_point(field_get:speechly.slu.v1.WLUIntent.intent)
  return _internal_intent();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void WLUIntent::set_intent(ArgT0&& arg0, ArgT... args) {
 
 intent_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:speechly.slu.v1.WLUIntent.intent)
}
inline std::string* WLUIntent::mutable_intent() {
  std::string* _s = _internal_mutable_intent();
  // @@protoc_insertion_point(field_mutable:speechly.slu.v1.WLUIntent.intent)
  return _s;
}
inline const std::string& WLUIntent::_internal_intent() const {
  return intent_.Get();
}
inline void WLUIntent::_internal_set_intent(const std::string& value) {
  
  intent_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* WLUIntent::_internal_mutable_intent() {
  
  return intent_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* WLUIntent::release_intent() {
  // @@protoc_insertion_point(field_release:speechly.slu.v1.WLUIntent.intent)
  return intent_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void WLUIntent::set_allocated_intent(std::string* intent) {
  if (intent != nullptr) {
    
  } else {
    
  }
  intent_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), intent,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:speechly.slu.v1.WLUIntent.intent)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace v1
}  // namespace slu
}  // namespace speechly

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_speechly_2fslu_2fv1_2fwlu_2eproto
