// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.17.3
// source: speechly/config/v1/model.proto

package configv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BaseModel describes the base model that is used as basis for adaptation.
type BaseModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The human readable name of the base model
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The alias of the model used in the config file
	Alias string `protobuf:"bytes,2,opt,name=alias,proto3" json:"alias,omitempty"`
	// Is the model available for the current tier
	IsAvailable bool `protobuf:"varint,3,opt,name=is_available,json=isAvailable,proto3" json:"is_available,omitempty"`
	// Does the model allow downloading on-device model bundles
	IsDownloadable bool `protobuf:"varint,4,opt,name=is_downloadable,json=isDownloadable,proto3" json:"is_downloadable,omitempty"`
}

func (x *BaseModel) Reset() {
	*x = BaseModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_speechly_config_v1_model_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BaseModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseModel) ProtoMessage() {}

func (x *BaseModel) ProtoReflect() protoreflect.Message {
	mi := &file_speechly_config_v1_model_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseModel.ProtoReflect.Descriptor instead.
func (*BaseModel) Descriptor() ([]byte, []int) {
	return file_speechly_config_v1_model_proto_rawDescGZIP(), []int{0}
}

func (x *BaseModel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BaseModel) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *BaseModel) GetIsAvailable() bool {
	if x != nil {
		return x.IsAvailable
	}
	return false
}

func (x *BaseModel) GetIsDownloadable() bool {
	if x != nil {
		return x.IsDownloadable
	}
	return false
}

var File_speechly_config_v1_model_proto protoreflect.FileDescriptor

var file_speechly_config_v1_model_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x73, 0x70, 0x65, 0x65, 0x63, 0x68, 0x6c, 0x79, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x12, 0x73, 0x70, 0x65, 0x65, 0x63, 0x68, 0x6c, 0x79, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x2e, 0x76, 0x31, 0x22, 0x81, 0x01, 0x0a, 0x09, 0x42, 0x61, 0x73, 0x65, 0x4d, 0x6f, 0x64,
	0x65, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x12, 0x21, 0x0a, 0x0c,
	0x69, 0x73, 0x5f, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0b, 0x69, 0x73, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x12,
	0x27, 0x0a, 0x0f, 0x69, 0x73, 0x5f, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x61, 0x62,
	0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0e, 0x69, 0x73, 0x44, 0x6f, 0x77, 0x6e,
	0x6c, 0x6f, 0x61, 0x64, 0x61, 0x62, 0x6c, 0x65, 0x42, 0x73, 0x0a, 0x16, 0x63, 0x6f, 0x6d, 0x2e,
	0x73, 0x70, 0x65, 0x65, 0x63, 0x68, 0x6c, 0x79, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e,
	0x76, 0x31, 0x42, 0x0a, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01,
	0x5a, 0x1b, 0x73, 0x70, 0x65, 0x65, 0x63, 0x68, 0x6c, 0x79, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x2f, 0x76, 0x31, 0x3b, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x76, 0x31, 0xa2, 0x02, 0x03,
	0x53, 0x43, 0x58, 0xaa, 0x02, 0x12, 0x53, 0x70, 0x65, 0x65, 0x63, 0x68, 0x6c, 0x79, 0x2e, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x12, 0x53, 0x70, 0x65, 0x65, 0x63,
	0x68, 0x6c, 0x79, 0x5c, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x5c, 0x56, 0x31, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_speechly_config_v1_model_proto_rawDescOnce sync.Once
	file_speechly_config_v1_model_proto_rawDescData = file_speechly_config_v1_model_proto_rawDesc
)

func file_speechly_config_v1_model_proto_rawDescGZIP() []byte {
	file_speechly_config_v1_model_proto_rawDescOnce.Do(func() {
		file_speechly_config_v1_model_proto_rawDescData = protoimpl.X.CompressGZIP(file_speechly_config_v1_model_proto_rawDescData)
	})
	return file_speechly_config_v1_model_proto_rawDescData
}

var file_speechly_config_v1_model_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_speechly_config_v1_model_proto_goTypes = []interface{}{
	(*BaseModel)(nil), // 0: speechly.config.v1.BaseModel
}
var file_speechly_config_v1_model_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_speechly_config_v1_model_proto_init() }
func file_speechly_config_v1_model_proto_init() {
	if File_speechly_config_v1_model_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_speechly_config_v1_model_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BaseModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_speechly_config_v1_model_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_speechly_config_v1_model_proto_goTypes,
		DependencyIndexes: file_speechly_config_v1_model_proto_depIdxs,
		MessageInfos:      file_speechly_config_v1_model_proto_msgTypes,
	}.Build()
	File_speechly_config_v1_model_proto = out.File
	file_speechly_config_v1_model_proto_rawDesc = nil
	file_speechly_config_v1_model_proto_goTypes = nil
	file_speechly_config_v1_model_proto_depIdxs = nil
}
