// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: speechly/identity/v2/identity_api.proto

#include "speechly/identity/v2/identity_api.pb.h"
#include "speechly/identity/v2/identity_api.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace speechly {
namespace identity {
namespace v2 {

static const char* IdentityAPI_method_names[] = {
  "/speechly.identity.v2.IdentityAPI/Login",
};

std::unique_ptr< IdentityAPI::Stub> IdentityAPI::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< IdentityAPI::Stub> stub(new IdentityAPI::Stub(channel));
  return stub;
}

IdentityAPI::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_Login_(IdentityAPI_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status IdentityAPI::Stub::Login(::grpc::ClientContext* context, const ::speechly::identity::v2::LoginRequest& request, ::speechly::identity::v2::LoginResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Login_, context, request, response);
}

void IdentityAPI::Stub::experimental_async::Login(::grpc::ClientContext* context, const ::speechly::identity::v2::LoginRequest* request, ::speechly::identity::v2::LoginResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Login_, context, request, response, std::move(f));
}

void IdentityAPI::Stub::experimental_async::Login(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::speechly::identity::v2::LoginResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Login_, context, request, response, std::move(f));
}

void IdentityAPI::Stub::experimental_async::Login(::grpc::ClientContext* context, const ::speechly::identity::v2::LoginRequest* request, ::speechly::identity::v2::LoginResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Login_, context, request, response, reactor);
}

void IdentityAPI::Stub::experimental_async::Login(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::speechly::identity::v2::LoginResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Login_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::speechly::identity::v2::LoginResponse>* IdentityAPI::Stub::AsyncLoginRaw(::grpc::ClientContext* context, const ::speechly::identity::v2::LoginRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::speechly::identity::v2::LoginResponse>::Create(channel_.get(), cq, rpcmethod_Login_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::speechly::identity::v2::LoginResponse>* IdentityAPI::Stub::PrepareAsyncLoginRaw(::grpc::ClientContext* context, const ::speechly::identity::v2::LoginRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::speechly::identity::v2::LoginResponse>::Create(channel_.get(), cq, rpcmethod_Login_, context, request, false);
}

IdentityAPI::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      IdentityAPI_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< IdentityAPI::Service, ::speechly::identity::v2::LoginRequest, ::speechly::identity::v2::LoginResponse>(
          std::mem_fn(&IdentityAPI::Service::Login), this)));
}

IdentityAPI::Service::~Service() {
}

::grpc::Status IdentityAPI::Service::Login(::grpc::ServerContext* context, const ::speechly::identity::v2::LoginRequest* request, ::speechly::identity::v2::LoginResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace speechly
}  // namespace identity
}  // namespace v2

